server:
  port: 5432

spring:
  datasource:
    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/camisasdb}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate   # usamos Flyway para crear/sembrar
    open-in-view: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true   # Esta l√≠nea es clave para resolver el problema

management:
  endpoints:
    web:
      exposure:
        include: health,info
